spring:
  h2:
    console.enabled: true
    username: sa
    password: planosaude
    driverClassName: org.h2.Driver
  datasource:
    url: jdbc:h2:file:/data/demo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: user
      password: planosaude